

services:
  postgres:
    image: postgres:17
    container_name: ticket_app_db
    environment:
      POSTGRES_DB: ticket_db 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_interface
    environment:
      PGADMIN_DEFAULT_EMAIL: abdullamaseeh123@gmail.com 
      PGADMIN_DEFAULT_PASSWORD: '%T55tt567'
      PGADMIN_DEFAULT_SERVER_MODE: 'FALSE'
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
